"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CACHE_CONFIGS = exports.memoryConfig = exports.cacheConfig = exports.defaultConfig = exports.config = exports.filterIssuesByLineRange = exports.hashText = exports.buildPartialLines = exports.findContainingNode = exports.findBestContainingMemberRangeForChanges = exports.findBestContainingMemberRange = exports.findBestContainingRangeForChanges = exports.findBestContainingRange = exports.diagnosticsTestUtils = exports.includesKeyword = exports.hasStructuralTokens = exports.sanitizeStructuralText = exports.stripCommentsFromLine = exports.buildAnalysisContext = exports.collectIncludeAliasesFromAst = exports.collectTypesFromAst = exports.analyzeThriftText = exports.analyzeThriftAst = exports.formatThriftContent = exports.ThriftFormatter = exports.walkNodes = exports.nodePathFromLeaf = exports.collectTopLevelTypes = exports.collectIncludes = exports.findSmallestNodeAtPosition = exports.rangeSize = exports.positionInRange = exports.sliceTextByRange = exports.createInteractionBlock = exports.createServiceBlock = exports.createEnumBlock = exports.createStructBlock = exports.createDocument = exports.createField = exports.nodes = exports.ThriftParser = exports.SelectionRange = exports.DiagnosticSeverity = exports.SymbolKind = exports.DocumentSymbol = exports.TextEdit = exports.Location = exports.Uri = exports.Range = exports.Position = void 0;
exports.formatMb = exports.ReportBuilder = exports.MemoryMonitor = exports.hashContent = exports.isFresh = exports.isExpired = exports.makeUriContentKey = exports.makeUriRangeKey = exports.makeLineRangeKey = exports.LruCache = exports.MemoryAwareCacheManager = exports.CacheManager = exports.ErrorHandler = exports.lineRangeFromChange = exports.rangeContainsLineRange = exports.rangeIntersectsLineRange = exports.lineRangeLineCount = exports.collapseLineRanges = exports.mergeLineRanges = exports.normalizeLineRange = exports.createLineRange = exports.registerAllCacheConfigs = exports.validateCacheConfig = exports.updateCacheConfig = exports.getAllCacheConfigs = void 0;
var types_1 = require("./types");
Object.defineProperty(exports, "Position", { enumerable: true, get: function () { return types_1.Position; } });
Object.defineProperty(exports, "Range", { enumerable: true, get: function () { return types_1.Range; } });
Object.defineProperty(exports, "Uri", { enumerable: true, get: function () { return types_1.Uri; } });
Object.defineProperty(exports, "Location", { enumerable: true, get: function () { return types_1.Location; } });
Object.defineProperty(exports, "TextEdit", { enumerable: true, get: function () { return types_1.TextEdit; } });
Object.defineProperty(exports, "DocumentSymbol", { enumerable: true, get: function () { return types_1.DocumentSymbol; } });
Object.defineProperty(exports, "SymbolKind", { enumerable: true, get: function () { return types_1.SymbolKind; } });
Object.defineProperty(exports, "DiagnosticSeverity", { enumerable: true, get: function () { return types_1.DiagnosticSeverity; } });
Object.defineProperty(exports, "SelectionRange", { enumerable: true, get: function () { return types_1.SelectionRange; } });
var parser_1 = require("./ast/parser");
Object.defineProperty(exports, "ThriftParser", { enumerable: true, get: function () { return parser_1.ThriftParser; } });
exports.nodes = __importStar(require("./ast/nodes.types"));
var factory_1 = require("./ast/factory");
Object.defineProperty(exports, "createField", { enumerable: true, get: function () { return factory_1.createField; } });
Object.defineProperty(exports, "createDocument", { enumerable: true, get: function () { return factory_1.createDocument; } });
Object.defineProperty(exports, "createStructBlock", { enumerable: true, get: function () { return factory_1.createStructBlock; } });
Object.defineProperty(exports, "createEnumBlock", { enumerable: true, get: function () { return factory_1.createEnumBlock; } });
Object.defineProperty(exports, "createServiceBlock", { enumerable: true, get: function () { return factory_1.createServiceBlock; } });
Object.defineProperty(exports, "createInteractionBlock", { enumerable: true, get: function () { return factory_1.createInteractionBlock; } });
var text_utils_1 = require("./ast/text-utils");
Object.defineProperty(exports, "sliceTextByRange", { enumerable: true, get: function () { return text_utils_1.sliceTextByRange; } });
var utils_1 = require("./ast/utils");
Object.defineProperty(exports, "positionInRange", { enumerable: true, get: function () { return utils_1.positionInRange; } });
Object.defineProperty(exports, "rangeSize", { enumerable: true, get: function () { return utils_1.rangeSize; } });
Object.defineProperty(exports, "findSmallestNodeAtPosition", { enumerable: true, get: function () { return utils_1.findSmallestNodeAtPosition; } });
Object.defineProperty(exports, "collectIncludes", { enumerable: true, get: function () { return utils_1.collectIncludes; } });
Object.defineProperty(exports, "collectTopLevelTypes", { enumerable: true, get: function () { return utils_1.collectTopLevelTypes; } });
Object.defineProperty(exports, "nodePathFromLeaf", { enumerable: true, get: function () { return utils_1.nodePathFromLeaf; } });
Object.defineProperty(exports, "walkNodes", { enumerable: true, get: function () { return utils_1.walkNodes; } });
var index_1 = require("./formatter/index");
Object.defineProperty(exports, "ThriftFormatter", { enumerable: true, get: function () { return index_1.ThriftFormatter; } });
var formatter_core_1 = require("./formatter/formatter-core");
Object.defineProperty(exports, "formatThriftContent", { enumerable: true, get: function () { return formatter_core_1.formatThriftContent; } });
var analyzer_1 = require("./diagnostics/rules/analyzer");
Object.defineProperty(exports, "analyzeThriftAst", { enumerable: true, get: function () { return analyzer_1.analyzeThriftAst; } });
Object.defineProperty(exports, "analyzeThriftText", { enumerable: true, get: function () { return analyzer_1.analyzeThriftText; } });
var include_resolver_1 = require("./diagnostics/include-resolver");
Object.defineProperty(exports, "collectTypesFromAst", { enumerable: true, get: function () { return include_resolver_1.collectTypesFromAst; } });
var analysis_context_1 = require("./diagnostics/rules/analysis-context");
Object.defineProperty(exports, "collectIncludeAliasesFromAst", { enumerable: true, get: function () { return analysis_context_1.collectIncludeAliasesFromAst; } });
Object.defineProperty(exports, "buildAnalysisContext", { enumerable: true, get: function () { return analysis_context_1.buildAnalysisContext; } });
var utils_2 = require("./diagnostics/utils");
Object.defineProperty(exports, "stripCommentsFromLine", { enumerable: true, get: function () { return utils_2.stripCommentsFromLine; } });
Object.defineProperty(exports, "sanitizeStructuralText", { enumerable: true, get: function () { return utils_2.sanitizeStructuralText; } });
Object.defineProperty(exports, "hasStructuralTokens", { enumerable: true, get: function () { return utils_2.hasStructuralTokens; } });
Object.defineProperty(exports, "includesKeyword", { enumerable: true, get: function () { return utils_2.includesKeyword; } });
Object.defineProperty(exports, "diagnosticsTestUtils", { enumerable: true, get: function () { return utils_2.diagnosticsTestUtils; } });
Object.defineProperty(exports, "findBestContainingRange", { enumerable: true, get: function () { return utils_2.findBestContainingRange; } });
Object.defineProperty(exports, "findBestContainingRangeForChanges", { enumerable: true, get: function () { return utils_2.findBestContainingRangeForChanges; } });
Object.defineProperty(exports, "findBestContainingMemberRange", { enumerable: true, get: function () { return utils_2.findBestContainingMemberRange; } });
Object.defineProperty(exports, "findBestContainingMemberRangeForChanges", { enumerable: true, get: function () { return utils_2.findBestContainingMemberRangeForChanges; } });
Object.defineProperty(exports, "findContainingNode", { enumerable: true, get: function () { return utils_2.findContainingNode; } });
Object.defineProperty(exports, "buildPartialLines", { enumerable: true, get: function () { return utils_2.buildPartialLines; } });
Object.defineProperty(exports, "hashText", { enumerable: true, get: function () { return utils_2.hashText; } });
Object.defineProperty(exports, "filterIssuesByLineRange", { enumerable: true, get: function () { return utils_2.filterIssuesByLineRange; } });
var index_2 = require("./config/index");
Object.defineProperty(exports, "config", { enumerable: true, get: function () { return index_2.config; } });
Object.defineProperty(exports, "defaultConfig", { enumerable: true, get: function () { return index_2.config; } });
Object.defineProperty(exports, "cacheConfig", { enumerable: true, get: function () { return index_2.cacheConfig; } });
Object.defineProperty(exports, "memoryConfig", { enumerable: true, get: function () { return index_2.memoryConfig; } });
var cache_config_1 = require("./config/cache-config");
Object.defineProperty(exports, "CACHE_CONFIGS", { enumerable: true, get: function () { return cache_config_1.CACHE_CONFIGS; } });
Object.defineProperty(exports, "getAllCacheConfigs", { enumerable: true, get: function () { return cache_config_1.getAllCacheConfigs; } });
Object.defineProperty(exports, "updateCacheConfig", { enumerable: true, get: function () { return cache_config_1.updateCacheConfig; } });
Object.defineProperty(exports, "validateCacheConfig", { enumerable: true, get: function () { return cache_config_1.validateCacheConfig; } });
Object.defineProperty(exports, "registerAllCacheConfigs", { enumerable: true, get: function () { return cache_config_1.registerAllCacheConfigs; } });
var line_range_1 = require("./utils/line-range");
Object.defineProperty(exports, "createLineRange", { enumerable: true, get: function () { return line_range_1.createLineRange; } });
Object.defineProperty(exports, "normalizeLineRange", { enumerable: true, get: function () { return line_range_1.normalizeLineRange; } });
Object.defineProperty(exports, "mergeLineRanges", { enumerable: true, get: function () { return line_range_1.mergeLineRanges; } });
Object.defineProperty(exports, "collapseLineRanges", { enumerable: true, get: function () { return line_range_1.collapseLineRanges; } });
Object.defineProperty(exports, "lineRangeLineCount", { enumerable: true, get: function () { return line_range_1.lineRangeLineCount; } });
Object.defineProperty(exports, "rangeIntersectsLineRange", { enumerable: true, get: function () { return line_range_1.rangeIntersectsLineRange; } });
Object.defineProperty(exports, "rangeContainsLineRange", { enumerable: true, get: function () { return line_range_1.rangeContainsLineRange; } });
Object.defineProperty(exports, "lineRangeFromChange", { enumerable: true, get: function () { return line_range_1.lineRangeFromChange; } });
var error_handler_1 = require("./utils/error-handler");
Object.defineProperty(exports, "ErrorHandler", { enumerable: true, get: function () { return error_handler_1.ErrorHandler; } });
var cache_manager_1 = require("./utils/cache-manager");
Object.defineProperty(exports, "CacheManager", { enumerable: true, get: function () { return cache_manager_1.CacheManager; } });
Object.defineProperty(exports, "MemoryAwareCacheManager", { enumerable: true, get: function () { return cache_manager_1.MemoryAwareCacheManager; } });
var optimized_lru_cache_1 = require("./utils/optimized-lru-cache");
Object.defineProperty(exports, "LruCache", { enumerable: true, get: function () { return optimized_lru_cache_1.LruCache; } });
var cache_keys_1 = require("./utils/cache-keys");
Object.defineProperty(exports, "makeLineRangeKey", { enumerable: true, get: function () { return cache_keys_1.makeLineRangeKey; } });
Object.defineProperty(exports, "makeUriRangeKey", { enumerable: true, get: function () { return cache_keys_1.makeUriRangeKey; } });
Object.defineProperty(exports, "makeUriContentKey", { enumerable: true, get: function () { return cache_keys_1.makeUriContentKey; } });
var cache_expiry_1 = require("./utils/cache-expiry");
Object.defineProperty(exports, "isExpired", { enumerable: true, get: function () { return cache_expiry_1.isExpired; } });
Object.defineProperty(exports, "isFresh", { enumerable: true, get: function () { return cache_expiry_1.isFresh; } });
Object.defineProperty(exports, "hashContent", { enumerable: true, get: function () { return cache_expiry_1.hashContent; } });
var memory_monitor_1 = require("./utils/memory-monitor");
Object.defineProperty(exports, "MemoryMonitor", { enumerable: true, get: function () { return memory_monitor_1.MemoryMonitor; } });
var report_builder_1 = require("./utils/report-builder");
Object.defineProperty(exports, "ReportBuilder", { enumerable: true, get: function () { return report_builder_1.ReportBuilder; } });
Object.defineProperty(exports, "formatMb", { enumerable: true, get: function () { return report_builder_1.formatMb; } });
//# sourceMappingURL=index.js.map